### ISSUE TITLE
微博热搜话题有重复，多次出现混乱；知乎热搜部分标题有空格，导致超链接无效；

### ISSUE THREAD

**Issue by Wym1ng** [justjavac/weibo-trending-hot-search#11]
RT，辛苦大佬！不知是否方便抽空处理一下呢，期待能修复。

**Comment by justjavac** [comment]
https://github.com/justjavac/zhihu-trending-top-search/commit/f2c657bfcd25cba05a2ba4d1084bde88ee79338c

**Comment by justjavac** [comment]
微博热搜是根据 url 做的去重复，可能是因为微博的相同话题使用了不同的 url 导致的

**Comment by Wym1ng** [comment]
> 微博热搜是根据 url 做的去重复，可能是因为微博的相同话题使用了不同的 url 导致的

看微博热搜重复的标题是相同的，是否能根据文本去重呢？这样看起来整洁方便很多。期待大佬评估一下
