### ISSUE TITLE
实现原理问题

### ISSUE THREAD

**Issue by z1x1ang** [justjavac/weibo-trending-hot-search#4]
大神，你好。我在github上看到你的关于微博、知乎、等等这些热搜的项目，想请问下你是怎么实现的呢？是把这个代码部署到了服务器上并且是设置的定时任务吗？你是用的什么服务器呢？谢谢

**Comment by justjavac** [comment]
我是用的 GitHub Actions，https://github.com/justjavac/weibo-trending-hot-search/blob/master/.github/workflows/schedule.yml
